"""remove native enum

Revision ID: 9327852ca796
Revises: 9ea4c196ad1a
Create Date: 2026-03-02 17:02:27.518083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9327852ca796'
down_revision: Union[str, Sequence[str], None] = '9ea4c196ad1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'status',
               existing_type=mysql.ENUM('open', 'closed'),
               type_=sa.Enum('open', 'closed', 'cancelled', name='statusenum', native_enum=False),
               existing_nullable=False)
    op.alter_column('tickets', 'progress',
               existing_type=mysql.ENUM('waiting', 'in_progress', 'feedback', 'awaiting_confirmation', 'done'),
               type_=sa.Enum('waiting', 'in_progress', 'feedback', 'awaiting_confirmation', 'done', name='progressenum', native_enum=False),
               existing_nullable=False)
    op.alter_column('tickets', 'priority',
               existing_type=mysql.ENUM('low', 'medium', 'high'),
               type_=sa.Enum('low', 'medium', 'high', name='priorityenum', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('admin', 'agent', 'client_manager', 'client_receptionist'),
               type_=sa.Enum('admin', 'agent', 'client_manager', 'client_receptionist', name='roleenum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'agent', 'client_manager', 'client_receptionist', name='roleenum', native_enum=False),
               type_=mysql.ENUM('admin', 'agent', 'client_manager', 'client_receptionist'),
               existing_nullable=False)
    op.alter_column('tickets', 'priority',
               existing_type=sa.Enum('low', 'medium', 'high', name='priorityenum', native_enum=False),
               type_=mysql.ENUM('low', 'medium', 'high'),
               existing_nullable=False)
    op.alter_column('tickets', 'progress',
               existing_type=sa.Enum('waiting', 'in_progress', 'feedback', 'awaiting_confirmation', 'done', name='progressenum', native_enum=False),
               type_=mysql.ENUM('waiting', 'in_progress', 'feedback', 'awaiting_confirmation', 'done'),
               existing_nullable=False)
    op.alter_column('tickets', 'status',
               existing_type=sa.Enum('open', 'closed', 'cancelled', name='statusenum', native_enum=False),
               type_=mysql.ENUM('open', 'closed'),
               existing_nullable=False)
    # ### end Alembic commands ###
